working on multiply

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -1,7 +1,7 @@
 #!/bin/bash -e
 
-# This a helper function to output floating point/decimal division
-# It takes two integer arguments and divides them to return the decimal value
+# This is a helper function to output floating point/decimal division
+# It takes two integers as arguments and divides them to return the decimal value
 # Full credit to user bebbo in:
 # https://stackoverflow.com/questions/12722095/how-do-i-use-floating-point-division-in-bash
 div() {
@@ -16,7 +16,7 @@ div() {
 ############################################################################
 # Function dims takes a file with a numbers matrix as an argument and prints 
 # the dimensions of the matrix as the number of rows, followed by a space, 
-# then the number of columns.
+# then the number of columns. Use of array is discouraged.
 ############################################################################
 dims(){
 	if [ "$#" -eq 1 ] #If number of arguments is 1
@@ -98,7 +98,7 @@ transpose(){
 # element is the mean of column one, the second element is the mean of column two, 
 # and so on. Do not use any other languages other than bash shell scripting: 
 # this means that, among others, awk, sed, tcl, bc, perl, & the python languages 
-# and tools are off-limits for this assignment.
+# and tools are off-limits for this assignment.Use of array is discouraged.
 ############################################################################
 mean () {
 	trap "find . -maxdepth 1 -name 'mean_temp.*' -exec rm -f {} \;" INT HUP TERM
@@ -168,10 +168,10 @@ mean () {
 # add should return an error if the matrices do not have the same dimensions.
 # Do not use any other languages other than bash shell scripting: 
 # this means that, among others, awk, sed, tcl, bc, perl, & the python languages 
-# and tools are off-limits for this assignment.
+# and tools are off-limits for this assignment. Use of array is discouraged.
 ####################################################################################
 add(){
-	if [ "$#" != 2 ] #If number of arguments is 1
+	if [ "$#" != 2 ]
 	then
 		#Number of supplied arguments is not 2
 		echo "Invalid number of supplied arguments"
@@ -180,7 +180,7 @@ add(){
 
 	find . -maxdepth 1 -name 'add_temp.*' -exec rm -f {} \;
 
-	#Get nummer of lines and display without the iflle's name
+	#Get nummer of lines
 	lineCnt1=$( wc --lines $1 | cut -d' ' --fields=1 )
 	lineCnt2=$( wc --lines $2 | cut -d' ' --fields=1 )
 
@@ -196,11 +196,8 @@ add(){
 		exit 1
 	fi
 
-	# Store numbers in temp file in single row
-	# Each column in argument file is transposed
-	# into a row in temp file
-
-	#track file count
+	# Store numbers in seperate temp files
+	# track file count
 	f_cnt=1
 	while read line
 	do
@@ -259,9 +256,97 @@ add(){
 	find . -maxdepth 1 -name 'add_temp*' -exec rm -f {} \;
 }
 
+########################################################################################
+# multiply should take an MxN and NxP matrix and produce an MxP matrix. 
+# Note that, unlike addition, matrix multiplication is not commutative. That is A*B != B*A.
+# Do not use any other languages other than bash shell scripting: 
+# this means that, among others, awk, sed, tcl, bc, perl, & the python languages 
+# and tools are off-limits for this assignment. Use of array is discouraged.
+########################################################################################
+multiply(){
+	if [ "$#" != 2 ]
+	then
+		#Number of supplied arguments is not 2
+		echo "Invalid number of supplied arguments"
+		exit 1
+	fi
 
-$1 "${@:2}"
-#add m1 m1
+	#Get nummer of rows and columns in each matrix
+	lineCnt1=$( wc --lines $1 | cut -d' ' --fields=1 )
+	lineCnt2=$( wc --lines $2 | cut -d' ' --fields=1 )
+	colCnt1=$( head --lines=1 $1 | wc -w )
+	colCnt2=$( head --lines=1 $2 | wc -w )
+
+	if [ $colCnt1 != $lineCnt2 ]
+	then
+		#Number of supplied arguments is not 2
+		echo "Mtrices cannot be multiplied"
+		exit 1
+	fi
+
+	# Store numbers in seperate temp files
+	# track file count
+	f_cnt=1
+	while read line
+	do
+		for i in $line
+		do
+			# Write the number into a file
+			printf "" > prod_temp.$f_cnt
+			printf "$i\n" >> prod_temp.$f_cnt
+			f_cnt=$(expr $f_cnt + 1 )
+		done
+	done < $1 # Read file supplied in argument 1
+
+	while read line
+	do
+		for i in $line
+		do
+			# Write the number into a file
+			printf "" > prod_temp.$f_cnt
+			printf "$i " >> prod_temp.$f_cnt
+			f_cnt=$(expr $f_cnt + 1 )
+		done
+	done < $2 # Read file supplied in argument 2
+
+	row_cnt=1 # Count rows
+	start=1	  # set count start position
+	f_cnt=$start # 1st matrix file count
+	mult=$(($lineCnt1 * $colCnt1 + $f_cnt)) # 2nd matrix count
+	printf "" > prod.temp.o # output file
+	
+	while [ $row_cnt -le $lineCnt1 ]
+	do
+		sum=0 # running total for m1 row m3 column
+		for ((i=1;i<=colCnt1;i++)); 
+		do
+			# Get the two numbers and add to the running sum
+			n1=$( head -c1 prod_temp.$f_cnt )
+			n2=$( head -c1 prod_temp.$mult )
+			sum=$(($sum + ( $n1 * $n2 )))
+			printf "$sum\t" >> prod.temp.o
+
+			printf "rc: $row_cnt; col: $i; file1: $f_cnt; file2: $mult\n"
+			mult=$( expr $mult + $colCnt2 )
+			f_cnt=$( expr $f_cnt + 1 )
+		done
+
+		row_cnt=$(($row_cnt + 1))
+		mult=$(($lineCnt1 * $colCnt1 + $start + 1 ))
+	done
+
+	# Output results and remove temp files
+	# find . -maxdepth 1 -name 'prod_temp*' -exec rm -f {} \;
+}
+
+# tst(){
+# 	ftst=./tst.o
+# 	TST= $( ls *prod* ) > $ftst
+# 	cat ftst
+# }
+
+#$1 "${@:2}"
+multiply m1 m2
 echo -e "\n$1 exit with $?"
 
 
