transpose complete

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ############################################################################
-# Function dims takes a files with a numbers matrix as an argument and prints 
+# Function dims takes a file with a numbers matrix as an argument and prints 
 # the dimensions of the matrix as the number of rows, followed by a space, 
 # then the number of columns.
 ############################################################################
@@ -23,14 +23,65 @@ dims(){
 	fi
 }
 
-
+############################################################################
+# Function transpose takes a file with a numbers matrix as an argument and  
+# reflects the elements of the matrix along the main diagonal. 
+# Thus, an MxN matrix becomes an NxM matrix and the values along the main diagonal 
+# remain unchanged. Use of array is discouraged.
+############################################################################
 transpose(){
-	printf "Called transpose with $1\n"
+
+	if [ "$#" != 1 ] #If number of arguments != 1
+	then
+		echo "Invalid number of supplied arguments"
+		exit 1
+	fi
+	
+	#Get nummer of lines and columns in argument file
+	lineCnt=$( wc --lines $1 | cut -d' ' --fields=1 ) 
+	colCnt=$( head --lines=1 $1 | wc -w )
+
+	# Create one file for each column
+	x=$colCnt
+	while [ $x -gt 0 ]; 
+	do 
+		# Create new temp file or clear previously created files
+		touch tr_temp_$x
+		printf "" > tr_temp_$x
+		x=$(($x-1))
+	done
+
+	# Store numbers in temp file in single row
+	# Each column in argument file is transposed 
+	# into a row in temp file
+	while read line
+	do
+		#track column count
+		c_cnt=1
+		for i in $line
+		do
+			# Write the number into a file
+			printf "$i\t" >> tr_temp_$c_cnt
+			c_cnt=`expr $c_cnt + 1 `
+		done
+	done < $1 # Read file supplied in argument 1
+
+	# cat out temp files in ascending order
+	COUNTER=1
+	while [  $COUNTER -le $colCnt ]
+	do
+		cat tr_temp_$COUNTER
+		printf "\n"
+		#echo $( cat tr_temp_$COUNTER ) 
+		let COUNTER=COUNTER+1 
+	done
+	
+	#remov temp files
+	find . -maxdepth 1 -name "tr_temp_*" -exec rm -f {} \;
 }
 
 #"$@"
 $1 "${@:2}"
-echo "$1 exited with $?"
+echo -e "\n$1 exit with $?"
 
-echo 'Done'
 
