working on add

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -100,7 +100,7 @@ transpose(){
 # and tools are off-limits for this assignment.
 ############################################################################
 mean () {
-	trap "find . -maxdepth 1 -name 'mean_temp.*' -exec rm -f {} \;" INT HUP TERM
+	trap "find . -maxdepth 1 -name 'add_temp.*' -exec rm -f {} \;" INT HUP TERM
 	if [ "$#" != 1 ] #If number of arguments != 1
 	then
 		echo "Invalid number of supplied arguments"
@@ -118,7 +118,7 @@ mean () {
 	do 
 		# Create new temp file or clear previously created files
 		touch mean_temp.$x
-		#printf "" > mean_temp.$x
+		printf "" > mean_temp.$x
 		x=$(($x-1))
 	done
 
@@ -162,7 +162,116 @@ mean () {
 	find . -maxdepth 1 -name 'mean_temp*' -exec rm -f {} \;
 }
 
+
+add(){
+	if [ "$#" != 2 ] #If number of arguments is 1
+	then
+		#Number of supplied arguments is not 2
+		echo "Invalid number of supplied arguments"
+		exit 1
+	fi
+
+	#Get nummer of lines and display without the iflle's name
+	lineCnt1=$( wc --lines $1 | cut -d' ' --fields=1 )
+	lineCnt2=$( wc --lines $2 | cut -d' ' --fields=1 )
+
+	#Get the first line and count the number of words
+	colCnt1=$( head --lines=1 $1 | wc -w )
+	colCnt2=$( head --lines=1 $2 | wc -w )
+	coldbl=$(($colCnt1 * 2))
+
+	if [ $lineCnt1 -ne $lineCnt2 ] || [ $colCnt1 -ne $colCnt2 ]
+	then
+		# Supplied matrices are not equal
+		echo "Supplied matrices are not equal"
+		exit 1
+	fi
+
+	# Create one file for each column
+	x=$coldbl
+	while [ $x -gt 0 ];
+	do
+		# Create new temp file or clear previously created files
+		touch add_temp_$x
+		printf "" > add_temp_$x
+		x=$(($x-1))
+	done
+
+	# Store numbers in temp file in single row
+	# Each column in argument file is transposed
+	# into a row in temp file
+
+	#track file count
+	f_cnt=1
+	while read line
+	do
+		for i in $line
+		do
+			# Write the number into a file
+			printf "$i " >> add_temp.$f_cnt
+			f_cnt=$(expr $f_cnt + 1 )
+		done
+	done < $1 # Read file supplied in argument 1
+
+	while read line
+	do
+		for i in $line
+		do
+			# Write the number into a file
+			printf "$i " >> add_temp.$f_cnt
+			f_cnt=$(expr $f_cnt + 1 )
+		done
+	done < $2 # Read file supplied in argument 2
+
+	#Calculate the sums and store in a temp file
+	cnt=1
+	#touch add_temp.o # Create temp file
+	cat > add_temp.o
+	while [ $cnt -le $(( $lineCnt1 * 2 )) ]
+	do
+		cnt2=$( expr $cnt + 8 )
+		printf "\n" >> add_temp.$cnt
+		printf "\n" >> add_temp.$cnt2
+		
+		# Sum the numbers
+		sum=0
+		while read line
+		do
+			for i in $line
+			do
+				sum=$( expr $sum + $i )
+			done
+		done < mean_temp.$cnt		
+
+		if [ $(($cnt % 2)) != 0]
+		then
+			printf "Mod 2 != 0\n"
+			while read line
+			do
+				for i in $line
+				do
+					sum=$( expr $sum + $i )
+					printf "$sum\t" >> add_temp.o
+				done
+			done < mean_temp.$cnt2
+		else
+			while read line
+			do
+				for i in $line
+				do
+					sum=$( expr $sum + $i )
+					printf "$sum\n" >> add_temp.o
+				done
+			done < mean_temp.$cnt2
+		fi
+		cnt=$(expr $cnt + 1 )	
+	done
+	cat add_temp.o
+}
+
+
 $1 "${@:2}"
+#add m1 m1
 echo -e "\n$1 exit with $?"
 
 
